name: OpenAPI docs check

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Generate API documentation
        run: |
          source venv/bin/activate
          python manage.py generateschema --file openapi-schema.yml

      - name: Check if docs are up to date
        run: |
          git diff --exit-code openapi-schema.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
